name: Daily Main.py Execution

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC or 08:00 UTC+8

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run main.py
        run: python main.py