name: Daily send Execution  # Workflow的名称

on:
  workflow_dispatch:  # 允许手动触发workflow
  schedule:  # 定时自动运行workflow
    - cron: "0 0 * * *"  # 每天UTC时间00:00或者UTC+8时间08:00运行

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pwd
          pip install -r requirements.txt

      - name: Run test.py
        run: python main.py

# #如果测试成功，合并到main分支
#   merge:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Merge to main
#         run: |
#           git config --global user.email "2362422778@qq.com"
#           git config --global user.name "awz66661"
#           git checkout main
#           git merge test
#           git push