name: Daily Main.py Execution

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run main.py
        run: python main.py